const data = {
   products:[
      {
         _id: '1',
         name: 'Nike Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 10,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '2',
         name: 'Adidas Slim Shirt',
         category: 'Shirts',
         image: '/images/p2.jpg',
         price: 12,
         countInStock: 20,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '3',
         name: 'Under Armour Slim Shirt',
         category: 'Shirts',
         image: '/images/p3.jpg',
         price: 150,
         countInStock: 0,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '4',
         name: 'Reebok Slim Shirt',
         category: 'Shirts',
         image: '/images/p4.jpg',
         price: 120,
         countInStock: 1,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '5',
         name: 'Puma Slim Shirt',
         category: 'Shirts',
         image: '/images/p5.jpg',
         price: 120,
         countInStock: 10,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '6',
         name: 'Asics Slim Shirt',
         category: 'Shirts',
         image: '/images/p6.jpg',
         price: 120,
         countInStock: 12,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '7',
         name: 'Callaway Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 6,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '8',
         name: 'Russell Athletic Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 142,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '9',
         name: 'Champion Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 11,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         _id: '10',
         name: 'Fila Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 6,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
   ],
}

// Command below is needed when this file is imported by another file
export default data;