import bcrypt from 'bcryptjs';

const data = {
   users:[
      {
         name:'Victor',
         email: 'victor@mail.com',
         password: bcrypt.hashSync('1234', 8),
         isAdmin: true,

      },
      {
         name:'John',
         email: 'john@mail.com',
         password: bcrypt.hashSync('1234', 8),
         isAdmin: false,
      },
   ],
   products:[
      {
         name: 'Nike Slim Shirt',
         category: 'Shirts',
         image: '/images/yamazaki-18-year-old-whisky.jpg',
         price: 120,
         countInStock: 10,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Adidas Slim Shirt',
         category: 'Shirts',
         image: '/images/p2.jpg',
         price: 12,
         countInStock: 20,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Under Armour Slim Shirt',
         category: 'Shirts',
         image: '/images/p3.jpg',
         price: 150,
         countInStock: 0,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Reebok Slim Shirt',
         category: 'Shirts',
         image: '/images/p4.jpg',
         price: 120,
         countInStock: 1,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Puma Slim Shirt',
         category: 'Shirts',
         image: '/images/p5.jpg',
         price: 120,
         countInStock: 10,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Asics Slim Shirt',
         category: 'Shirts',
         image: '/images/p6.jpg',
         price: 120,
         countInStock: 12,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Callaway Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 6,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Russell Athletic Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 142,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Champion Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 11,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
      {
         name: 'Fila Slim Shirt',
         category: 'Shirts',
         image: '/images/p1.jpg',
         price: 120,
         countInStock: 6,
         brand: 'Nike',
         rating: 4.5,
         numReviews: 10,
         description: 'high quality product',
      },
   ],
}

// Command below is needed when this file is imported by another file
export default data;